---
- name: os x playbook
  hosts: local
  roles:
    - { role: brew, tags: ['brew'] }
    - { role: cask, tags: ['cask'] }
    - { role: lang, tags: ['lang'] }
    - { role: fonts, tags: ['fonts'] }
    # - system
    # - files
