---

- name: ensure homebrew is at the newest version
  homebrew: update_homebrew=yes

- name: ensure taps are installed
  homebrew_tap: tap={{ item }}
  with_items: "{{ taps }}"

- name: check packages are installed
  shell: brew list | grep "^{{ item }}$"
  register: installed_packages
  with_items: "{{ packages }}"
  ignore_errors: true

- name: ensure packages are installed
  homebrew: name={{ item }} state=latest
  with_items: "{{ packages }}"
  when: item not in installed_packages.results | map(attribute='stdout')

- name: ensure packages are up-to-date
  homebrew: upgrade_all=yes
